# Generated by Django 6.0.5 on 2026-07-20 23:01

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True)),
                ('reset_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('security_stamp', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('city_state', models.CharField(blank=True, max_length=255)),
                ('faith', models.CharField(blank=True, max_length=50)),
                ('denomination', models.CharField(blank=True, max_length=255)),
                ('place_of_worship', models.CharField(blank=True, max_length=255)),
                ('highest_qualification', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('workplace', models.CharField(blank=True, max_length=255)),
                ('genotype', models.CharField(blank=True, max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('love_language', models.CharField(blank=True, max_length=50)),
                ('preferred_age_min', models.IntegerField(blank=True, null=True)),
                ('preferred_age_max', models.IntegerField(blank=True, null=True)),
                ('interests', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('short_bio', models.TextField(blank=True)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('is_banned', models.BooleanField(default=False)),
                ('state_of_residence', models.CharField(blank=True, max_length=255)),
                ('state_of_origin', models.CharField(blank=True, max_length=255)),
                ('ethnic_group', models.CharField(blank=True, max_length=255)),
                ('about_self', models.TextField(blank=True)),
                ('seeking_description', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('profile_view', 'Profile Viewed'), ('like', 'Liked'), ('match', 'Matched'), ('message', 'Message Sent'), ('counselling', 'Counselling Session')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
