# Generated by Django 6.0.5 on 2026-07-27 15:34

import django.db.models.deletion
from django.db import migrations, models


def set_empty_denomination_to_null(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(denomination='').update(denomination=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_empty_denomination_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='denomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.denomination'),
        ),
    ]
