# Generated by Django 6.0.5 on 2026-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alcohol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='complexion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='deal_breakers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_spoken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personality_traits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_height_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_height_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_tribe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='willing_to_relocate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
