# Generated by Django 6.0.5 on 2026-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relationship_status',
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
