# Generated by Django 6.0.5 on 2026-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_replace_relationship_status_with_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_tribe',
            field=models.TextField(blank=True),
        ),
    ]
