# Generated by Django 6.0.5 on 2026-07-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_change_preferred_tribe_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_location',
            field=models.TextField(blank=True),
        ),
    ]
