# Generated by Django 6.0.5 on 2026-08-08 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_change_preferred_location_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('TERMS', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy'), ('REFUND_POLICY', 'Refund & Cancellation Policy')], max_length=20)),
                ('document_version', models.CharField(default='1.0', max_length=20)),
                ('accepted', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'consent_type'], name='accounts_us_user_id_1d0f83_idx'), models.Index(fields=['user', 'consent_type', '-accepted_at'], name='accounts_us_user_id_72f046_idx')],
            },
        ),
    ]
