# Generated by Django 4.2.29 on 2026-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_browser',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='last_device',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ua',
            field=models.TextField(blank=True, default=''),
        ),
    ]
