# Generated by Django 6.0.5 on 2026-09-22 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_last_browser_user_last_device_and_more'),
        ('profiles', '0006_hobby_language_locationoption_vibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_hobby',
            field=models.CharField(blank=True, default='', help_text='Custom hobby when Other is selected', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Height in centimetres', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies_m2m',
            field=models.ManyToManyField(blank=True, related_name='users_hobbies', to='profiles.hobby'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_m2m',
            field=models.ManyToManyField(blank=True, related_name='users_languages', to='profiles.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='profiles.locationoption'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_weight_max',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_weight_min',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='user',
            name='vibes',
            field=models.ManyToManyField(blank=True, related_name='users', to='profiles.vibe'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_age_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_age_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_height_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_height_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
