# Generated by Django 4.2.29 on 2026-09-14 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_message_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.TextField(blank=True, default='', help_text='First characters of the blocked message, for admin review.')),
                ('matched_terms', models.TextField(blank=True, default='', help_text='The exact snippets that triggered the block.')),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('channel', models.CharField(blank=True, default='ws', help_text='"ws" for WebSocket messages, "rest" for REST API messages.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='chat.conversation')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chat_moderation_logs', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='chat_modera_created_40cbfb_idx'), models.Index(fields=['category'], name='chat_modera_categor_f0296b_idx'), models.Index(fields=['sender'], name='chat_modera_sender__65c0e2_idx')],
            },
        ),
    ]
