# Generated by Django 6.0.5 on 2026-08-06 13:29

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_audio'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_period', models.DateField(blank=True, null=True)),
                ('audio_minutes_used', models.PositiveIntegerField(default=0)),
                ('video_minutes_used', models.PositiveIntegerField(default=0)),
                ('counselling_sessions_used', models.PositiveIntegerField(default=0)),
                ('profile_views_today', models.PositiveIntegerField(default=0)),
                ('likes_today', models.PositiveIntegerField(default=0)),
                ('saves_today', models.PositiveIntegerField(default=0)),
                ('daily_period', models.DateField(blank=True, null=True)),
                ('active_conversations_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 6, 13, 29, 9, 836998, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('billed_minutes', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='chat.conversation')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('message_limit', models.PositiveIntegerField(blank=True, help_text='Max messages per counting period. Null = unlimited.', null=True)),
                ('message_reset_period', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('active_conversation_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_minutes_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('video_minutes_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_view_limit_daily', models.PositiveIntegerField(blank=True, null=True)),
                ('like_limit_daily', models.PositiveIntegerField(blank=True, null=True)),
                ('save_limit_daily', models.PositiveIntegerField(blank=True, null=True)),
                ('can_use_advanced_filters', models.BooleanField(default=False)),
                ('can_see_likes', models.BooleanField(default=False)),
                ('can_see_visitors', models.BooleanField(default=False)),
                ('can_send_voice_notes', models.BooleanField(default=False)),
                ('can_use_read_receipts', models.BooleanField(default=False)),
                ('can_appear_featured', models.BooleanField(default=False)),
                ('can_use_profile_boost', models.BooleanField(default=False)),
                ('discover_priority', models.IntegerField(default=0)),
                ('free_counselling_sessions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
                'indexes': [models.Index(fields=['slug'], name='subscriptio_slug_3cc181_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_dd0689_idx')],
            },
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'end_date'], name='subscriptio_status_93cc56_idx'),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='subscriptions.usersubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['initiated_by', 'call_type'], name='subscriptio_initiat_a448e8_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['ended_at'], name='subscriptio_ended_a_165e1b_idx'),
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
