# Generated by Django 6.0.5 on 2026-08-06 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_metadata_payment_period_end_and_more'),
        ('subscriptions', '0003_subscriptionplan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='payments_pa_transac_2dc1cb_idx'),
        ),
    ]
