# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_gateway_payment_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify'), ('opay', 'OPay')], default='paystack', max_length=20),
        ),
    ]