# Generated by Django 4.2.29 on 2026-08-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_alter_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('opay', 'OPay'), ('flutterwave', 'Flutterwave')], default='paystack', max_length=20),
        ),
    ]
