# Generated by Django 4.2.29 on 2026-08-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave')], default='flutterwave', max_length=20),
        ),
    ]
