# Generated by Django 6.0.5 on 2026-07-20 23:12

import admins.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('role', models.CharField(choices=[('operations_admin', 'Operations Admin'), ('moderator', 'Moderator'), ('counsellor', 'Counsellor')], max_length=50)),
                ('department', models.CharField(blank=True, choices=[('management', 'Management'), ('operations', 'Operations'), ('moderation', 'Moderation'), ('counselling', 'Counselling'), ('support', 'Support')], default='', max_length=100)),
                ('token', models.CharField(default=admins.models.generate_invitation_token, max_length=64, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=admins.models.default_invitation_expiry)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Invitation',
                'verbose_name_plural': 'Admin Invitations',
                'db_table': 'admins_admininvitation',
                'ordering': ['-created_at'],
            },
        ),
    ]
