# Generated by Django 4.2.29 on 2026-09-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_adminprofile_approved_at_adminprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvitation',
            name='role',
            field=models.CharField(choices=[('operations_admin', 'Operation Manager'), ('moderator', 'Community Manager'), ('counsellor', 'Support and Counselling Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Platform Administrator'), ('operations_admin', 'Operation Manager'), ('moderator', 'Community Manager'), ('counsellor', 'Support and Counselling Manager')], max_length=50),
        ),
    ]
