# Generated by Django 6.0.5 on 2026-09-17 16:56

import admins.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_admininvitation_role_alter_adminprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('blog', 'Blog Article'), ('devotional', 'Devotional'), ('article', 'Article')], default='blog', max_length=30)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('author_name', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=admins.models.default_published_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'db_table': 'admins_contentitem',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('group', models.CharField(blank=True, default='', max_length=60)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('is_secret', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Setting',
                'verbose_name_plural': 'Integration Settings',
                'db_table': 'admins_integrationsetting',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SeoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, default='', max_length=160)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.CharField(blank=True, default='', max_length=500)),
                ('og_title', models.CharField(blank=True, default='', max_length=160)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.CharField(blank=True, default='', max_length=500)),
                ('canonical_url', models.CharField(blank=True, default='', max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, default='', max_length=60)),
                ('google_site_verification', models.CharField(blank=True, default='', max_length=200)),
                ('robots', models.CharField(blank=True, default='index, follow', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
                'db_table': 'admins_seosetting',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_user', 'New User'), ('user_login', 'User Login'), ('new_admin', 'New Admin'), ('admin_login', 'Admin Login'), ('match', 'Match'), ('counselling', 'Counselling'), ('photo', 'Photo'), ('bot_ticket', 'Bot Ticket'), ('system', 'System'), ('custom', 'Custom')], default='system', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('event_key', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'db_table': 'admins_adminnotification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='admins_admi_recipie_2e4426_idx'), models.Index(fields=['recipient', 'is_read'], name='admins_admi_recipie_e443f3_idx')],
            },
        ),
    ]
