# Generated by Django 6.0.5 on 2026-07-27 15:39

from django.db import migrations
from django.utils.text import slugify
import re


def normalize_name(name):
    name = (name or "").strip()
    name = re.sub(r'\s+', ' ', name)
    name = re.sub(r'[^\w\s\-\.\,\&\'\(\)]', '', name)
    return name


def seed_denominations(apps, schema_editor):
    Denomination = apps.get_model('profiles', 'Denomination')
    names = [
        'Redeemed Christian Church of God (RCCG)',
        'Living Faith Church (Winners Chapel)',
        'Mountain of Fire and Miracles',
        'Christ Embassy',
        'Dunamis International Gospel Centre',
        'House on the Rock',
        'Salvation Ministries',
        'Deeper Life Bible Church',
        'Assemblies of God',
        'Foursquare Gospel Church',
        'Christ Apostolic Church (CAC)',
        'Roman Catholic Church',
        'Anglican Communion',
        'Methodist Church',
        'Baptist Convention',
        'Presbyterian Church',
        'ECWA',
        'Celestial Church of Christ',
        'Cherubim and Seraphim',
        'Church of God Mission',
        "The Lord's Chosen",
        'Streams of Joy',
        'Harvesters International Christian Centre',
        'Commonwealth of Zion Assembly (COZA)',
        'Daystar Christian Centre',
        'Kingsway International Christian Centre (KICC)',
        'Pentecostal',
        'New Generation Church',
        'Others',
    ]
    for name in names:
        normalized = normalize_name(name)
        if normalized:
            Denomination.objects.get_or_create(
                name=normalized,
                defaults={
                    'slug': slugify(normalized) or 'unknown',
                    'approved': True,
                    'is_active': True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_denominations, migrations.RunPython.noop),
    ]
