# Generated by Django 4.2.29 on 2026-09-17 14:11

from django.db import migrations, models


def backfill_review_status(apps, schema_editor):
    Photo = apps.get_model('profiles', 'Photo')
    Photo.objects.filter(approved=True, review_status='pending').update(review_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_ensure_denominations'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Explicit moderation outcome: pending review, approved, or rejected.', max_length=10),
        ),
        migrations.RunPython(backfill_review_status, migrations.RunPython.noop),
    ]
