from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.AdminDashboardView.as_view(), name='admin-dashboard'),
    path('users/', views.AdminUserListView.as_view(), name='admin-user-list'),
    path('users/<int:user_id>/', views.AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('users/<int:user_id>/suspend/', views.AdminUserSuspendView.as_view(), name='admin-user-suspend'),
    path('users/<int:user_id>/ban/', views.AdminUserBanView.as_view(), name='admin-user-ban'),
    path('users/<int:user_id>/reinstate/', views.AdminUserReinstateView.as_view(), name='admin-user-reinstate'),
    path('photos/approve/', views.AdminPhotoApprovalView.as_view(), name='admin-photo-approve'),
    path('counselling/', views.AdminCounsellingListView.as_view(), name='admin-counselling-list'),
    path('counselling/<int:session_id>/', views.AdminCounsellingSessionUpdateView.as_view(), name='admin-counselling-update'),
    path('payments/', views.AdminPaymentListView.as_view(), name='admin-payment-list'),
    path('subscriptions/', views.AdminSubscriptionListView.as_view(), name='admin-subscription-list'),
    path('reports/', views.AdminReportListView.as_view(), name='admin-report-list'),
    path('roles/', views.AdminRoleListView.as_view(), name='admin-role-list'),
    path('roles/assign/', views.AdminRoleAssignView.as_view(), name='admin-role-assign'),
    path('roles/<int:user_id>/remove/', views.AdminRoleRemoveView.as_view(), name='admin-role-remove'),
    path('signup/', views.AdminSignupView.as_view(), name='admin-signup'),
    path('login/', views.AdminLoginView.as_view(), name='admin-login'),
    path('invitations/', views.AdminInvitationListCreateView.as_view(), name='admin-invitation-list'),
    path('invitations/<int:pk>/revoke/', views.AdminInvitationRevokeView.as_view(), name='admin-invitation-revoke'),
    path('pending/', views.AdminPendingListView.as_view(), name='admin-pending-list'),
    path('admins/<int:user_id>/approve/', views.AdminApproveView.as_view(), name='admin-approve'),
    path('users/<int:user_id>/reset-password/', views.AdminResetPasswordView.as_view(), name='admin-reset-password'),
    path('audit-log/', views.AdminAuditLogView.as_view(), name='admin-audit-log'),
    path('settings/', views.AdminSettingsView.as_view(), name='admin-settings'),
    path('notifications/broadcast/', views.AdminNotificationBroadcastView.as_view(), name='admin-notification-broadcast'),
    path('notifications/feed/', views.AdminNotificationFeedView.as_view(), name='admin-notification-feed'),
    path('admins/<int:user_id>/block/', views.AdminBlockUnblockView.as_view(), name='admin-block-unblock'),
    path('heartbeat/', views.AdminHeartbeatView.as_view(), name='admin-heartbeat'),
    path('denominations/', views.AdminDenominationListView.as_view(), name='admin-denomination-list'),
    path('denominations/create/', views.AdminDenominationCreateView.as_view(), name='admin-denomination-create'),
    path('denominations/<int:denomination_id>/update/', views.AdminDenominationUpdateView.as_view(), name='admin-denomination-update'),
    path('denominations/<int:denomination_id>/delete/', views.AdminDenominationDeleteView.as_view(), name='admin-denomination-delete'),
    path('pending-denominations/', views.AdminPendingDenominationListView.as_view(), name='admin-pending-denomination-list'),
    path('pending-denominations/<int:pending_id>/approve/', views.AdminPendingDenominationApproveView.as_view(), name='admin-pending-denomination-approve'),
    path('pending-denominations/<int:pending_id>/reject/', views.AdminPendingDenominationRejectView.as_view(), name='admin-pending-denomination-reject'),
]
